// ============================================================================
// Mock Data for AbiaEats
// Used when Supabase is not connected or returns no data
// ============================================================================

import type { Restaurant, MenuItem } from '@/types/database';

// ============================================================================
// Mock Restaurants
// ============================================================================

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'mock-mama-put',
    owner_id: 'mock-owner-1',
    name: 'Mama Put Kitchen',
    slug: 'mama-put-kitchen',
    description: 'Authentic Nigerian home cooking. The best jollof rice and egusi soup in Aba.',
    phone: '+2348012345678',
    address: '15 Asa Road, Aba',
    city: 'aba',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['local', 'rice dishes', 'pepper soup'],
    delivery_fee: 500,
    min_delivery_time: 25,
    max_delivery_time: 35,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: true,
    is_active: true,
    total_orders: 234,
    total_revenue: 890000,
    average_rating: 4.8,
    rating_count: 156,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mock-aba-grills',
    owner_id: 'mock-owner-2',
    name: 'Aba Grills & Shawarma',
    slug: 'aba-grills-shawarma',
    description: 'Best grills and shawarma in town. Fast service, fresh ingredients.',
    phone: '+2348023456789',
    address: '42 Azikiwe Road, Aba',
    city: 'aba',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['grills', 'shawarma', 'fast food'],
    delivery_fee: 400,
    min_delivery_time: 20,
    max_delivery_time: 30,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: true,
    is_active: true,
    total_orders: 312,
    total_revenue: 1250000,
    average_rating: 4.6,
    rating_count: 203,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mock-nkwobi-palace',
    owner_id: 'mock-owner-3',
    name: 'Nkwobi Palace',
    slug: 'nkwobi-palace',
    description: 'Premium traditional delicacies. Nkwobi, Isi ewu, and more.',
    phone: '+2348034567890',
    address: '8 Faulks Road, Aba',
    city: 'aba',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['local', 'pepper soup', 'grills'],
    delivery_fee: 600,
    min_delivery_time: 30,
    max_delivery_time: 45,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: true,
    is_active: true,
    total_orders: 187,
    total_revenue: 1680000,
    average_rating: 4.9,
    rating_count: 142,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mock-chicken-express',
    owner_id: 'mock-owner-4',
    name: 'Chicken Express',
    slug: 'chicken-express',
    description: 'Crispy fried chicken, burgers, and loaded fries. Quick and tasty.',
    phone: '+2348045678901',
    address: '23 Tenant Road, Aba',
    city: 'aba',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['fast food', 'grills', 'drinks'],
    delivery_fee: 350,
    min_delivery_time: 15,
    max_delivery_time: 25,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: true,
    is_active: true,
    total_orders: 456,
    total_revenue: 980000,
    average_rating: 4.5,
    rating_count: 289,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mock-sweet-bites',
    owner_id: 'mock-owner-5',
    name: 'Sweet Bites Bakery',
    slug: 'sweet-bites-bakery',
    description: 'Fresh pastries, cakes, bread, and small chops. Perfect for any occasion.',
    phone: '+2348056789012',
    address: '67 Park Road, Aba',
    city: 'aba',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['bakery', 'drinks'],
    delivery_fee: 300,
    min_delivery_time: 20,
    max_delivery_time: 35,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: true,
    is_active: true,
    total_orders: 198,
    total_revenue: 560000,
    average_rating: 4.7,
    rating_count: 134,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mock-umuahia-kitchen',
    owner_id: 'mock-owner-6',
    name: 'Umuahia Kitchen',
    slug: 'umuahia-kitchen',
    description: 'Home-style cooking from the heart of Umuahia. Soups, rice, and more.',
    phone: '+2348067890123',
    address: '12 Library Avenue, Umuahia',
    city: 'umuahia',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['local', 'rice dishes', 'pepper soup'],
    delivery_fee: 450,
    min_delivery_time: 25,
    max_delivery_time: 40,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: false,
    is_active: true,
    total_orders: 145,
    total_revenue: 670000,
    average_rating: 4.4,
    rating_count: 98,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mock-pizza-place',
    owner_id: 'mock-owner-7',
    name: 'Pizza & Wings Hub',
    slug: 'pizza-wings-hub',
    description: 'Wood-fired pizza, crispy wings, and cold drinks. Perfect for hangouts.',
    phone: '+2348078901234',
    address: '5 Brass Road, Aba',
    city: 'aba',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['fast food', 'grills', 'drinks'],
    delivery_fee: 500,
    min_delivery_time: 30,
    max_delivery_time: 45,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: true,
    is_active: true,
    total_orders: 267,
    total_revenue: 1120000,
    average_rating: 4.3,
    rating_count: 176,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'mock-smoothie-bar',
    owner_id: 'mock-owner-8',
    name: 'Fresh Squeeze Smoothie Bar',
    slug: 'fresh-squeeze-smoothie-bar',
    description: 'Fresh fruit smoothies, juices, parfaits, and healthy bowls.',
    phone: '+2348089012345',
    address: '31 Market Road, Aba',
    city: 'aba',
    image_url: null,
    cover_image_url: null,
    cuisine_tags: ['drinks', 'bakery'],
    delivery_fee: 300,
    min_delivery_time: 10,
    max_delivery_time: 20,
    commission_rate: 6,
    bank_name: null,
    bank_account_number: null,
    bank_account_name: null,
    is_open: true,
    is_active: true,
    total_orders: 378,
    total_revenue: 450000,
    average_rating: 4.8,
    rating_count: 245,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
];

// ============================================================================
// Mock Menu Items (per restaurant)
// ============================================================================

export const MOCK_MENU_ITEMS: Record<string, MenuItem[]> = {
  'mock-mama-put': [
    {
      id: 'menu-1-1',
      restaurant_id: 'mock-mama-put',
      name: 'Jollof Rice & Chicken',
      description: 'Smoky party jollof with a big piece of seasoned chicken',
      price: 2500,
      image_url: null,
      category: 'Rice Dishes',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-1-2',
      restaurant_id: 'mock-mama-put',
      name: 'Fried Rice & Chicken',
      description: 'Colorful fried rice with tender chicken and coleslaw',
      price: 2500,
      image_url: null,
      category: 'Rice Dishes',
      is_available: true,
      is_popular: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-1-3',
      restaurant_id: 'mock-mama-put',
      name: 'Egusi Soup & Pounded Yam',
      description: 'Rich egusi soup with assorted meat and smooth pounded yam',
      price: 3000,
      image_url: null,
      category: 'Soups & Swallows',
      is_available: true,
      is_popular: true,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-1-4',
      restaurant_id: 'mock-mama-put',
      name: 'Oha Soup & Fufu',
      description: 'Traditional oha soup with fresh oha leaves and stock fish',
      price: 2800,
      image_url: null,
      category: 'Soups & Swallows',
      is_available: true,
      is_popular: false,
      sort_order: 4,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-1-5',
      restaurant_id: 'mock-mama-put',
      name: 'Pepper Soup (Goat)',
      description: 'Spicy goat meat pepper soup with utazi leaves',
      price: 3500,
      image_url: null,
      category: 'Pepper Soup',
      is_available: true,
      is_popular: true,
      sort_order: 5,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-1-6',
      restaurant_id: 'mock-mama-put',
      name: 'White Rice & Stew',
      description: 'Plain white rice with tomato stew and assorted proteins',
      price: 2000,
      image_url: null,
      category: 'Rice Dishes',
      is_available: true,
      is_popular: false,
      sort_order: 6,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-1-7',
      restaurant_id: 'mock-mama-put',
      name: 'Bottled Water',
      description: 'Cold 75cl bottled water',
      price: 200,
      image_url: null,
      category: 'Drinks',
      is_available: true,
      is_popular: false,
      sort_order: 7,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-1-8',
      restaurant_id: 'mock-mama-put',
      name: 'Soft Drink (PET)',
      description: 'Coke, Fanta, Sprite, or Malt - 50cl',
      price: 350,
      image_url: null,
      category: 'Drinks',
      is_available: true,
      is_popular: false,
      sort_order: 8,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
  'mock-aba-grills': [
    {
      id: 'menu-2-1',
      restaurant_id: 'mock-aba-grills',
      name: 'Chicken Shawarma',
      description: 'Loaded chicken shawarma with fresh veggies and special sauce',
      price: 2000,
      image_url: null,
      category: 'Shawarma',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-2-2',
      restaurant_id: 'mock-aba-grills',
      name: 'Beef Shawarma',
      description: 'Premium beef shawarma with mayo, ketchup, and hot sauce',
      price: 2500,
      image_url: null,
      category: 'Shawarma',
      is_available: true,
      is_popular: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-2-3',
      restaurant_id: 'mock-aba-grills',
      name: 'Grilled Chicken (Full)',
      description: 'Whole grilled chicken with spicy pepper sauce',
      price: 5000,
      image_url: null,
      category: 'Grills',
      is_available: true,
      is_popular: true,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-2-4',
      restaurant_id: 'mock-aba-grills',
      name: 'Suya (Beef)',
      description: 'Spicy grilled beef suya with onions and pepper',
      price: 1500,
      image_url: null,
      category: 'Grills',
      is_available: true,
      is_popular: true,
      sort_order: 4,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-2-5',
      restaurant_id: 'mock-aba-grills',
      name: 'Chips & Chicken',
      description: 'Crispy fries with grilled chicken strips',
      price: 2000,
      image_url: null,
      category: 'Fast Food',
      is_available: true,
      is_popular: false,
      sort_order: 5,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-2-6',
      restaurant_id: 'mock-aba-grills',
      name: 'Chapman',
      description: 'Classic Nigerian Chapman cocktail with fruit slices',
      price: 1000,
      image_url: null,
      category: 'Drinks',
      is_available: true,
      is_popular: false,
      sort_order: 6,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
  'mock-nkwobi-palace': [
    {
      id: 'menu-3-1',
      restaurant_id: 'mock-nkwobi-palace',
      name: 'Nkwobi',
      description: 'Spicy cow foot in palm oil sauce — our signature dish',
      price: 4000,
      image_url: null,
      category: 'Specials',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-3-2',
      restaurant_id: 'mock-nkwobi-palace',
      name: 'Isi Ewu',
      description: 'Goat head pepper soup delicacy',
      price: 4500,
      image_url: null,
      category: 'Specials',
      is_available: true,
      is_popular: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-3-3',
      restaurant_id: 'mock-nkwobi-palace',
      name: 'Catfish Pepper Soup',
      description: 'Fresh catfish in aromatic spicy broth',
      price: 3500,
      image_url: null,
      category: 'Pepper Soup',
      is_available: true,
      is_popular: true,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-3-4',
      restaurant_id: 'mock-nkwobi-palace',
      name: 'Assorted Pepper Soup',
      description: 'Mixed meat pepper soup with cow tripe, liver, and kidney',
      price: 3000,
      image_url: null,
      category: 'Pepper Soup',
      is_available: true,
      is_popular: false,
      sort_order: 4,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-3-5',
      restaurant_id: 'mock-nkwobi-palace',
      name: 'Palm Wine (Fresh)',
      description: 'Freshly tapped palm wine — cold and sweet',
      price: 800,
      image_url: null,
      category: 'Drinks',
      is_available: true,
      is_popular: false,
      sort_order: 5,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
  'mock-chicken-express': [
    {
      id: 'menu-4-1',
      restaurant_id: 'mock-chicken-express',
      name: 'Fried Chicken (2pc)',
      description: 'Two pieces of crispy fried chicken',
      price: 1800,
      image_url: null,
      category: 'Chicken',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-4-2',
      restaurant_id: 'mock-chicken-express',
      name: 'Chicken Burger',
      description: 'Juicy chicken burger with lettuce, tomato, and cheese',
      price: 2200,
      image_url: null,
      category: 'Burgers',
      is_available: true,
      is_popular: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-4-3',
      restaurant_id: 'mock-chicken-express',
      name: 'Loaded Fries',
      description: 'Fries topped with cheese sauce and chicken bits',
      price: 1500,
      image_url: null,
      category: 'Sides',
      is_available: true,
      is_popular: false,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-4-4',
      restaurant_id: 'mock-chicken-express',
      name: 'Chicken Wings (6pc)',
      description: 'Crispy chicken wings with your choice of sauce',
      price: 2500,
      image_url: null,
      category: 'Chicken',
      is_available: true,
      is_popular: true,
      sort_order: 4,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-4-5',
      restaurant_id: 'mock-chicken-express',
      name: 'Milkshake',
      description: 'Creamy milkshake — vanilla, chocolate, or strawberry',
      price: 1200,
      image_url: null,
      category: 'Drinks',
      is_available: true,
      is_popular: false,
      sort_order: 5,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
  'mock-sweet-bites': [
    {
      id: 'menu-5-1',
      restaurant_id: 'mock-sweet-bites',
      name: 'Meat Pie',
      description: 'Flaky pastry filled with seasoned minced meat',
      price: 500,
      image_url: null,
      category: 'Pastries',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-5-2',
      restaurant_id: 'mock-sweet-bites',
      name: 'Chicken Pie',
      description: 'Pastry stuffed with seasoned chicken and vegetables',
      price: 600,
      image_url: null,
      category: 'Pastries',
      is_available: true,
      is_popular: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-5-3',
      restaurant_id: 'mock-sweet-bites',
      name: 'Doughnut (3pc)',
      description: 'Soft ring doughnuts with sugar coating',
      price: 600,
      image_url: null,
      category: 'Pastries',
      is_available: true,
      is_popular: false,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-5-4',
      restaurant_id: 'mock-sweet-bites',
      name: 'Small Chops (20pc)',
      description: 'Assorted small chops — spring rolls, samosa, puff puff, chicken strips',
      price: 3500,
      image_url: null,
      category: 'Party Packs',
      is_available: true,
      is_popular: true,
      sort_order: 4,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-5-5',
      restaurant_id: 'mock-sweet-bites',
      name: 'Cake Slice',
      description: 'Moist chocolate or vanilla cake slice',
      price: 1200,
      image_url: null,
      category: 'Cakes',
      is_available: true,
      is_popular: false,
      sort_order: 5,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
  'mock-umuahia-kitchen': [
    {
      id: 'menu-6-1',
      restaurant_id: 'mock-umuahia-kitchen',
      name: 'Abacha (African Salad)',
      description: 'Traditional Igbo salad made from dried cassava with ugba and palm oil',
      price: 1500,
      image_url: null,
      category: 'Local Dishes',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-6-2',
      restaurant_id: 'mock-umuahia-kitchen',
      name: 'Onugbu Soup & Garri',
      description: 'Bitter leaf soup with assorted meat and eba',
      price: 2500,
      image_url: null,
      category: 'Soups & Swallows',
      is_available: true,
      is_popular: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-6-3',
      restaurant_id: 'mock-umuahia-kitchen',
      name: 'Jollof Rice & Fish',
      description: 'Party jollof with grilled tilapia',
      price: 2800,
      image_url: null,
      category: 'Rice Dishes',
      is_available: true,
      is_popular: false,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
  'mock-pizza-place': [
    {
      id: 'menu-7-1',
      restaurant_id: 'mock-pizza-place',
      name: 'Pepperoni Pizza (Medium)',
      description: 'Classic pepperoni with mozzarella and tomato sauce',
      price: 4500,
      image_url: null,
      category: 'Pizza',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-7-2',
      restaurant_id: 'mock-pizza-place',
      name: 'BBQ Chicken Pizza',
      description: 'BBQ sauce base with chicken, peppers, and onions',
      price: 5000,
      image_url: null,
      category: 'Pizza',
      is_available: true,
      is_popular: true,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-7-3',
      restaurant_id: 'mock-pizza-place',
      name: 'Spicy Wings (8pc)',
      description: 'Buffalo-style hot wings with ranch dip',
      price: 3000,
      image_url: null,
      category: 'Wings',
      is_available: true,
      is_popular: true,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-7-4',
      restaurant_id: 'mock-pizza-place',
      name: 'Garlic Bread',
      description: 'Toasted garlic bread with herbs and butter',
      price: 1000,
      image_url: null,
      category: 'Sides',
      is_available: true,
      is_popular: false,
      sort_order: 4,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
  'mock-smoothie-bar': [
    {
      id: 'menu-8-1',
      restaurant_id: 'mock-smoothie-bar',
      name: 'Tropical Smoothie',
      description: 'Mango, pineapple, banana blend with yogurt',
      price: 1500,
      image_url: null,
      category: 'Smoothies',
      is_available: true,
      is_popular: true,
      sort_order: 1,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-8-2',
      restaurant_id: 'mock-smoothie-bar',
      name: 'Green Detox',
      description: 'Spinach, cucumber, apple, and ginger',
      price: 1800,
      image_url: null,
      category: 'Smoothies',
      is_available: true,
      is_popular: false,
      sort_order: 2,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-8-3',
      restaurant_id: 'mock-smoothie-bar',
      name: 'Fresh Orange Juice',
      description: 'Freshly squeezed orange juice — no sugar added',
      price: 1000,
      image_url: null,
      category: 'Juices',
      is_available: true,
      is_popular: true,
      sort_order: 3,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
    {
      id: 'menu-8-4',
      restaurant_id: 'mock-smoothie-bar',
      name: 'Acai Bowl',
      description: 'Acai bowl with granola, banana, and honey drizzle',
      price: 2500,
      image_url: null,
      category: 'Bowls',
      is_available: true,
      is_popular: true,
      sort_order: 4,
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-02-24T00:00:00Z',
    },
  ],
};

// ============================================================================
// Helper to get mock restaurant by ID
// ============================================================================

export function getMockRestaurant(id: string): Restaurant | undefined {
  return MOCK_RESTAURANTS.find((r) => r.id === id);
}

export function getMockMenuItems(restaurantId: string): MenuItem[] {
  return MOCK_MENU_ITEMS[restaurantId] || [];
}

// ============================================================================
// Category icon mapping for UI
// ============================================================================

export const CATEGORY_ICONS: Record<string, string> = {
  'all': '🍽️',
  'fast food': '🍔',
  'rice dishes': '🍚',
  'pepper soup': '🍲',
  'grills': '🍖',
  'shawarma': '🌯',
  'drinks': '🥤',
  'local': '🥘',
  'bakery': '🍞',
};
